--JOIN AND SUBQUERY ASSIGNMENT
SELECT * FROM Products ORDER BY ProductName
SELECT * FROM Categories
SELECT * FROM Orders
SELECT * FROM [dbo].[Employees]
SELECT * FROM Customers
SELECT * FROM [Order Details]


--1  LIST ALL THE PRODUCTS DETAILS WHOSE CATEGORY IS SAME AS 'TOFU'
SELECT * FROM Products P WHERE P.CategoryID IN (SELECT CategoryID FROM Products WHERE ProductName = 'TOFU')

--2  LIST ALL THE PRODUCTS DETAILS FOR THE CATEGORY 'BEVERAGES'
SELECT * FROM Products WHERE CategoryID IN (SELECT CategoryID FROM Categories WHERE CategoryName = 'BEVERAGES')
--3  LIST ALL THE ORDERS PLACED BY THE COMPANY NAME "ISLAND TRADING"
SELECT * FROM Orders WHERE ShipName = 'ISLAND TRADING'
--4  LIST COMPANY NAME AND NO OF ORDER COUNT PLACED BY EACH COMPANY
SELECT SHIPNAME, COUNT(ORDERID) FROM Orders GROUP BY ShipName
--5  LIST ORDERID, CUSTOMER_COMAPNAYNAME FOR ALL THE ORDERS WHICH ARE HANDLE BY THE EMPLOYEES WHOSE TITLE IS "SALES MANAGER"
SELECT ORDERID, SHIPNAME FROM Orders WHERE EmployeeID IN (SELECT EmployeeID FROM Employees WHERE Title = 'SALES MANAGER')
--6  LIST 3RD HIGHEST COSTLIEST PRODUCT
WITH RESULT AS
(
SELECT *, DENSE_RANK() OVER(ORDER BY UNITPRICE DESC) AS RANK FROM Products
)
SELECT * FROM RESULT WHERE RANK = 3
--7  FOR THE PRODUCT TABLE DISPLAY PRODUCTNAME AND CATEGORYNAME. ARRANGE AS PER THE CATEGORYNAME
SELECT P.PRODUCTNAME, C.CATEGORYNAME FROM Products P JOIN Categories C
ON P.CategoryID = C.CategoryID
ORDER BY C.CategoryName
--8  FOR THE ORDERS TABLE DISPLAY ORDERID CUSTOMER_COMPANYNAME AND EMPLOYEE_FULLNAME
SELECT O.ORDERID, C.CompanyName, E.FirstName + E.LastName AS EMP_NAME FROM Orders O JOIN Customers C
ON O.CustomerID = C.CustomerID JOIN Employees E
ON E.EmployeeID = O.EmployeeID

--9  LIST ORDERID, EMPLOYEE_FULLNAME, CUSTOMER_COMPANYNAME, CATEGORYNAME, SUPPLIER_COMPANYNAME, PRODUCTNAME, 
--ORDERDETAIS_UNIRPRICE, ORDERDETAILS_QUANTITY , NETSTOCK
SELECT O.OrderID, E.FirstName + E.LastName AS NAME,CUST.CompanyName, CAT.CategoryName, S.CompanyName, P.ProductName, OD.UnitPrice,
OD.Quantity  FROM Orders O LEFT JOIN Employees E
ON E.EmployeeID = O.EmployeeID LEFT JOIN Customers CUST 
ON CUST.CustomerID = O.CustomerID JOIN [Order Details] OD
ON OD.OrderID = O.OrderID JOIN Products P 
ON OD.ProductID = P.ProductID JOIN Categories CAT
ON CAT.CategoryID = P.CategoryID JOIN Suppliers S
ON S.SupplierID = P.SupplierID

--10  LIST ALL THE ORDERS (ORDERID, PRODUCTNAME) PLACED BY THE CUSTOMER IN LONDON

SELECT O.OrderID,P.ProductName FROM  Orders O  JOIN Customers CUST 
ON CUST.CustomerID = O.CustomerID JOIN [Order Details] OD
ON OD.OrderID = O.OrderID JOIN Products P 
ON OD.ProductID = P.ProductID
WHERE CUST.City = 'LONDON'

--11  FOR THE COSTLIEST PRODUCT DISPLAY PRODUCTNAME, UNITPRICE, CATEGORYNAME, SUPPLIER_CONTACTNAME

SELECT P.ProductName,P.UnitPrice,CAT.CategoryName, S.ContactName FROM Products P JOIN Categories CAT
ON CAT.CategoryID = P.CategoryID JOIN Suppliers S
ON S.SupplierID = P.SupplierID
WHERE P.UnitPrice IN (SELECT MAX(UnitPrice) FROM Products)

--12  LIST ALL THE PRODUCTNAME WHOSE ORDER PLACED IN MONTH OF AUGUST

SELECT P.ProductName FROM ORDERS O JOIN [Order Details] OD
ON OD.OrderID = O.OrderID JOIN Products P 
ON OD.ProductID = P.ProductID
WHERE MONTH(O.OrderDate) = 8

--13  LIST ORDERID, QUANTITY FOR ALL THE ORDERS. ASSIGNED RANK AS PER THE HIGHEST OT LOWEST QUANTITY. 
--DO NOT MISS ANY NUMBER WHILE ASSIGNING THE RANK

SELECT O.OrderID, OD.Quantity, DENSE_RANK() OVER(ORDER BY OD.QUANTITY DESC) AS RANK FROM ORDERS O JOIN [Order Details] OD
ON OD.OrderID = O.OrderID

--14 LIST ALL THE PRODUCTS FOR THE CATEGORY “DAIRY PRODUCT”

SELECT * FROM Products WHERE ProductID IN (SELECT PRODUCTID FROM Categories WHERE CategoryName = 'DAIRY PRODUCTS')

--15 LIST ALL THE PRODUCTS WHICH IS SUPPLIED BY THE COMPANY “BIGFOOT BREWERIES”  FOR THE CATEGORY “BEVERAGES”

SELECT P.* FROM Products P JOIN Categories CAT
ON CAT.CategoryID = P.CategoryID JOIN Suppliers S
ON S.SupplierID = P.SupplierID
WHERE CAT.CategoryName = 'BEVERAGES' AND S.CompanyName = 'BIGFOOT BREWERIES'

--16 PRINT   CATEGORYNAME , SUPPLIER COMAPNY NAME  AND PRODUCT COUNT FOR EACH CATEGORY AND SUPPLIER

SELECT CAT.CategoryName, S.CompanyName, COUNT(P.ProductID) AS COUNT FROM Products P JOIN Categories CAT
ON CAT.CategoryID = P.CategoryID JOIN Suppliers S
ON S.SupplierID = P.SupplierID
GROUP BY CAT.CategoryName, S.CompanyName

--17 PRINT REGION AND TERRITORYDESCRIPTION NAME IN ASCENDING ORDER
--18 PRINT  EMPLOYEES NAME, REGION NAME, CITY AND COUNTRY  --(CHECK FOR THE ERROR,  NO REGION RELATIONSHIP)

SELECT FirstName, Region, City, Country FROM Employees

--19 FOR EACH CATEGORIES PRINT CATEGORYNAME AND SUPPLIERS NAME

SELECT C.CategoryName, S.CompanyName FROM Categories C  LEFT JOIN Products P
ON C.CategoryID = P.CategoryID LEFT JOIN Suppliers S
ON S.SupplierID = P.SupplierID

--20 PRINT EMPLOYEE TITLEOFCOURTESY, EMPLOYEE FIRST + LASTNAME , EMPLOYEE TITLE, MANAGER TITLEOFCURTASY, 
--MANAGER FIRSTNAME + LASTNAME, MANAGER TITLE
SELECT E.TitleOfCourtesy, E.FirstName + E.LastName, E.Title, M.TitleOfCourtesy AS MGR, M.FirstName + M.LastName AS MGNAME,
 M.Title AS MGRTITLE FROM Employees E LEFT JOIN Employees M 
ON E.ReportsTo = M.EmployeeID